# Generated by Django 2.1.4 on 2018-12-29 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Button',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_no', models.CharField(max_length=5, unique=True)),
                ('image', models.ImageField(upload_to='buttons')),
                ('size', models.IntegerField(choices=[(14, 14), (15, 15), (16, 16), (17, 17), (18, 18), (19, 19), (20, 20), (21, 21), (22, 22), (23, 23), (24, 24), (25, 25), (26, 26), (27, 27), (28, 28), (29, 29), (30, 30), (31, 31), (32, 32), (33, 33), (34, 34), (35, 35), (36, 36)], default=14)),
                ('date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('price_unit', models.IntegerField(blank=True, default=1, null=True)),
                ('published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['model_no'],
            },
        ),
        migrations.CreateModel(
            name='ButtonCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('about', models.TextField(blank=True, max_length=400)),
            ],
            options={
                'verbose_name_plural': 'Button Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Qualities',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'qualities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
            options={
                'verbose_name_plural': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='button',
            name='button_type',
            field=models.ManyToManyField(related_name='btn_category', to='buttons.ButtonCategory'),
        ),
        migrations.AddField(
            model_name='button',
            name='qualities',
            field=models.ManyToManyField(blank=True, related_name='qualities', to='buttons.Qualities'),
        ),
        migrations.AddField(
            model_name='button',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='buttons.Tags'),
        ),
    ]
