# Generated by Django 2.1.4 on 2018-12-28 18:01

from django.db import migrations
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('buttons', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buttoncategory',
            name='cover',
        ),
        migrations.AlterField(
            model_name='button',
            name='image',
            field=s3direct.fields.S3DirectField(),
        ),
    ]
