# Generated by Django 2.1.4 on 2018-12-28 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buttons', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='button',
            name='image',
            field=models.ImageField(upload_to='buttons'),
        ),
    ]
